// Package orders_dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package orders_dto

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	externalRef0 "github.com/Staspol216/gh1/pkg/api/openapi/common"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for OrderStatus.
const (
	Delivered    OrderStatus = "delivered"
	None         OrderStatus = "none"
	Received     OrderStatus = "received"
	Refunded     OrderStatus = "refunded"
	Returned     OrderStatus = "returned"
	StorageEnded OrderStatus = "storage_ended"
)

// Valid indicates whether the value is a known member of the OrderStatus enum.
func (e OrderStatus) Valid() bool {
	switch e {
	case Delivered:
		return true
	case None:
		return true
	case Received:
		return true
	case Refunded:
		return true
	case Returned:
		return true
	case StorageEnded:
		return true
	default:
		return false
	}
}

// Defines values for OrderUpdateAction.
const (
	Deliver OrderUpdateAction = "deliver"
	Refund  OrderUpdateAction = "refund"
)

// Valid indicates whether the value is a known member of the OrderUpdateAction enum.
func (e OrderUpdateAction) Valid() bool {
	switch e {
	case Deliver:
		return true
	case Refund:
		return true
	default:
		return false
	}
}

// Defines values for PackagingType.
const (
	Bag      PackagingType = "bag"
	Box      PackagingType = "box"
	Membrana PackagingType = "membrana"
)

// Valid indicates whether the value is a known member of the PackagingType enum.
func (e PackagingType) Valid() bool {
	switch e {
	case Bag:
		return true
	case Box:
		return true
	case Membrana:
		return true
	default:
		return false
	}
}

// Order defines model for Order.
type Order struct {
	DeliveredDate  *time.Time    `json:"delivered_date,omitempty"`
	ExpirationDate time.Time     `json:"expiration_date"`
	History        []OrderRecord `json:"history"`
	Id             int64         `json:"id"`
	RecipientId    int64         `json:"recipient_id"`
	RefundedDate   *time.Time    `json:"refunded_date,omitempty"`
	ReturnedDate   *time.Time    `json:"returned_date,omitempty"`
	Status         OrderStatus   `json:"status"`
	Weight         float64       `json:"weight"`
	Worth          float64       `json:"worth"`
}

// OrderCreateRequest defines model for OrderCreateRequest.
type OrderCreateRequest struct {
	MembranaIncluded bool          `json:"membranaIncluded"`
	Order            OrderParams   `json:"order"`
	PackagingType    PackagingType `json:"packagingType"`
}

// OrderIDResponse defines model for OrderIDResponse.
type OrderIDResponse struct {
	OrderId int64 `json:"order_id"`
}

// OrderParams defines model for OrderParams.
type OrderParams struct {
	ExpirationDate time.Time `json:"expiration_date"`
	RecipientId    int64     `json:"recipient_id"`
	Weight         float64   `json:"weight"`
	Worth          float64   `json:"worth"`
}

// OrderRecord defines model for OrderRecord.
type OrderRecord struct {
	Description string      `json:"description"`
	Status      OrderStatus `json:"status"`
	Timestamp   time.Time   `json:"timestamp"`
}

// OrderStatus defines model for OrderStatus.
type OrderStatus string

// OrderUpdateAction defines model for OrderUpdateAction.
type OrderUpdateAction string

// OrderUpdateRequest defines model for OrderUpdateRequest.
type OrderUpdateRequest struct {
	Action      OrderUpdateAction `json:"action"`
	OrderIds    []int64           `json:"order_ids"`
	RecipientId int64             `json:"recipient_id"`
}

// PackagingType defines model for PackagingType.
type PackagingType string

// Limit defines model for limit.
type Limit = int

// Offset defines model for offset.
type Offset = string

// OrderID defines model for orderID.
type OrderID = int64

// RecipientID defines model for recipientID.
type RecipientID = int64

// CreateOrderResponse defines model for CreateOrderResponse.
type CreateOrderResponse = OrderIDResponse

// GetOrderResponse defines model for GetOrderResponse.
type GetOrderResponse = Order

// GetOrdersListResponse defines model for GetOrdersListResponse.
type GetOrdersListResponse struct {
	Orders []Order `json:"orders"`
}

// GetOrdersParams defines parameters for GetOrders.
type GetOrdersParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetOrdersHistoryParams defines parameters for GetOrdersHistory.
type GetOrdersHistoryParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetRefundedOrdersParams defines parameters for GetRefundedOrders.
type GetRefundedOrdersParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// DeleteOrderParams defines parameters for DeleteOrder.
type DeleteOrderParams struct {
	RecipientID RecipientID `form:"recipientID" json:"recipientID"`
}

// GetOrderParams defines parameters for GetOrder.
type GetOrderParams struct {
	RecipientID RecipientID `form:"recipientID" json:"recipientID"`
}

// UpdateOrdersJSONRequestBody defines body for UpdateOrders for application/json ContentType.
type UpdateOrdersJSONRequestBody = OrderUpdateRequest

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = OrderCreateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieve a list of Orders
	// (GET /orders)
	GetOrders(w http.ResponseWriter, r *http.Request, params GetOrdersParams)
	// Deliver or refund orders for recipient
	// (PATCH /orders)
	UpdateOrders(w http.ResponseWriter, r *http.Request)
	// Accept an order from courier
	// (POST /orders)
	CreateOrder(w http.ResponseWriter, r *http.Request)
	// Retrieve orders history
	// (GET /orders-history)
	GetOrdersHistory(w http.ResponseWriter, r *http.Request, params GetOrdersHistoryParams)
	// Retrieve refunded orders
	// (GET /orders/refunds)
	GetRefundedOrders(w http.ResponseWriter, r *http.Request, params GetRefundedOrdersParams)
	// Return order to courier
	// (DELETE /orders/{orderID})
	DeleteOrder(w http.ResponseWriter, r *http.Request, orderID OrderID, params DeleteOrderParams)
	// Retrieve order by ID for recipient
	// (GET /orders/{orderID})
	GetOrder(w http.ResponseWriter, r *http.Request, orderID OrderID, params GetOrderParams)
	// Health check
	// (GET /ping)
	GetPing(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Retrieve a list of Orders
// (GET /orders)
func (_ Unimplemented) GetOrders(w http.ResponseWriter, r *http.Request, params GetOrdersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Deliver or refund orders for recipient
// (PATCH /orders)
func (_ Unimplemented) UpdateOrders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Accept an order from courier
// (POST /orders)
func (_ Unimplemented) CreateOrder(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve orders history
// (GET /orders-history)
func (_ Unimplemented) GetOrdersHistory(w http.ResponseWriter, r *http.Request, params GetOrdersHistoryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve refunded orders
// (GET /orders/refunds)
func (_ Unimplemented) GetRefundedOrders(w http.ResponseWriter, r *http.Request, params GetRefundedOrdersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Return order to courier
// (DELETE /orders/{orderID})
func (_ Unimplemented) DeleteOrder(w http.ResponseWriter, r *http.Request, orderID OrderID, params DeleteOrderParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve order by ID for recipient
// (GET /orders/{orderID})
func (_ Unimplemented) GetOrder(w http.ResponseWriter, r *http.Request, orderID OrderID, params GetOrderParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /ping)
func (_ Unimplemented) GetPing(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetOrders operation middleware
func (siw *ServerInterfaceWrapper) GetOrders(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOrdersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrders(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateOrders operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateOrders(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateOrder(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrder(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrdersHistory operation middleware
func (siw *ServerInterfaceWrapper) GetOrdersHistory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOrdersHistoryParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrdersHistory(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRefundedOrders operation middleware
func (siw *ServerInterfaceWrapper) GetRefundedOrders(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRefundedOrdersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRefundedOrders(w, r, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOrder operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "orderID" -------------
	var orderID OrderID

	err = runtime.BindStyledParameterWithOptions("simple", "orderID", chi.URLParam(r, "orderID"), &orderID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteOrderParams

	// ------------- Required query parameter "recipientID" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "recipientID", r.URL.Query(), &params.RecipientID, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "recipientID"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recipientID", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOrder(w, r, orderID, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrder operation middleware
func (siw *ServerInterfaceWrapper) GetOrder(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "orderID" -------------
	var orderID OrderID

	err = runtime.BindStyledParameterWithOptions("simple", "orderID", chi.URLParam(r, "orderID"), &orderID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOrderParams

	// ------------- Required query parameter "recipientID" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "recipientID", r.URL.Query(), &params.RecipientID, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "recipientID"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recipientID", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrder(w, r, orderID, params)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPing operation middleware
func (siw *ServerInterfaceWrapper) GetPing(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPing(w, r)
	}))

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		handler = siw.HandlerMiddlewares[i](handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orders", wrapper.GetOrders)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/orders", wrapper.UpdateOrders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/orders", wrapper.CreateOrder)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orders-history", wrapper.GetOrdersHistory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orders/refunds", wrapper.GetRefundedOrders)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/orders/{orderID}", wrapper.DeleteOrder)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/orders/{orderID}", wrapper.GetOrder)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ping", wrapper.GetPing)
	})

	return r
}

type CreateOrderResponseJSONResponse OrderIDResponse

type GetOrderResponseJSONResponse Order

type GetOrdersListResponseJSONResponse struct {
	Orders []Order `json:"orders"`
}

type GetOrdersRequestObject struct {
	Params GetOrdersParams
}

type GetOrdersResponseObject interface {
	VisitGetOrdersResponse(w http.ResponseWriter) error
}

type GetOrders200JSONResponse struct {
	GetOrdersListResponseJSONResponse
}

func (response GetOrders200JSONResponse) VisitGetOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrders400JSONResponse struct {
	externalRef0.ApiErrorResponseJSONResponse
}

func (response GetOrders400JSONResponse) VisitGetOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrdersdefaultJSONResponse struct {
	Body       externalRef0.ApiError
	StatusCode int
}

func (response GetOrdersdefaultJSONResponse) VisitGetOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOrdersRequestObject struct {
	Body *UpdateOrdersJSONRequestBody
}

type UpdateOrdersResponseObject interface {
	VisitUpdateOrdersResponse(w http.ResponseWriter) error
}

type UpdateOrders204Response struct {
}

func (response UpdateOrders204Response) VisitUpdateOrdersResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type UpdateOrders400JSONResponse struct {
	externalRef0.ApiErrorResponseJSONResponse
}

func (response UpdateOrders400JSONResponse) VisitUpdateOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateOrdersdefaultJSONResponse struct {
	Body       externalRef0.ApiError
	StatusCode int
}

func (response UpdateOrdersdefaultJSONResponse) VisitUpdateOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrderRequestObject struct {
	Body *CreateOrderJSONRequestBody
}

type CreateOrderResponseObject interface {
	VisitCreateOrderResponse(w http.ResponseWriter) error
}

type CreateOrder201JSONResponse struct {
	CreateOrderResponseJSONResponse
}

func (response CreateOrder201JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrder400JSONResponse struct {
	externalRef0.ApiErrorResponseJSONResponse
}

func (response CreateOrder400JSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateOrderdefaultJSONResponse struct {
	Body       externalRef0.ApiError
	StatusCode int
}

func (response CreateOrderdefaultJSONResponse) VisitCreateOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrdersHistoryRequestObject struct {
	Params GetOrdersHistoryParams
}

type GetOrdersHistoryResponseObject interface {
	VisitGetOrdersHistoryResponse(w http.ResponseWriter) error
}

type GetOrdersHistory200JSONResponse struct {
	GetOrdersListResponseJSONResponse
}

func (response GetOrdersHistory200JSONResponse) VisitGetOrdersHistoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrdersHistory400JSONResponse struct {
	externalRef0.ApiErrorResponseJSONResponse
}

func (response GetOrdersHistory400JSONResponse) VisitGetOrdersHistoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrdersHistorydefaultJSONResponse struct {
	Body       externalRef0.ApiError
	StatusCode int
}

func (response GetOrdersHistorydefaultJSONResponse) VisitGetOrdersHistoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetRefundedOrdersRequestObject struct {
	Params GetRefundedOrdersParams
}

type GetRefundedOrdersResponseObject interface {
	VisitGetRefundedOrdersResponse(w http.ResponseWriter) error
}

type GetRefundedOrders200JSONResponse struct {
	GetOrdersListResponseJSONResponse
}

func (response GetRefundedOrders200JSONResponse) VisitGetRefundedOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRefundedOrders400JSONResponse struct {
	externalRef0.ApiErrorResponseJSONResponse
}

func (response GetRefundedOrders400JSONResponse) VisitGetRefundedOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetRefundedOrdersdefaultJSONResponse struct {
	Body       externalRef0.ApiError
	StatusCode int
}

func (response GetRefundedOrdersdefaultJSONResponse) VisitGetRefundedOrdersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOrderRequestObject struct {
	OrderID OrderID `json:"orderID"`
	Params  DeleteOrderParams
}

type DeleteOrderResponseObject interface {
	VisitDeleteOrderResponse(w http.ResponseWriter) error
}

type DeleteOrder204Response struct {
}

func (response DeleteOrder204Response) VisitDeleteOrderResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteOrder400JSONResponse struct {
	externalRef0.ApiErrorResponseJSONResponse
}

func (response DeleteOrder400JSONResponse) VisitDeleteOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOrder404JSONResponse externalRef0.ApiError

func (response DeleteOrder404JSONResponse) VisitDeleteOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteOrderdefaultJSONResponse struct {
	Body       externalRef0.ApiError
	StatusCode int
}

func (response DeleteOrderdefaultJSONResponse) VisitDeleteOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrderRequestObject struct {
	OrderID OrderID `json:"orderID"`
	Params  GetOrderParams
}

type GetOrderResponseObject interface {
	VisitGetOrderResponse(w http.ResponseWriter) error
}

type GetOrder200JSONResponse struct{ GetOrderResponseJSONResponse }

func (response GetOrder200JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrder400JSONResponse struct {
	externalRef0.ApiErrorResponseJSONResponse
}

func (response GetOrder400JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrder404JSONResponse externalRef0.ApiError

func (response GetOrder404JSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetOrderdefaultJSONResponse struct {
	Body       externalRef0.ApiError
	StatusCode int
}

func (response GetOrderdefaultJSONResponse) VisitGetOrderResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetPingRequestObject struct {
}

type GetPingResponseObject interface {
	VisitGetPingResponse(w http.ResponseWriter) error
}

type GetPing200TextResponse string

func (response GetPing200TextResponse) VisitGetPingResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

type GetPingdefaultJSONResponse struct {
	Body       externalRef0.ApiError
	StatusCode int
}

func (response GetPingdefaultJSONResponse) VisitGetPingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Retrieve a list of Orders
	// (GET /orders)
	GetOrders(ctx context.Context, request GetOrdersRequestObject) (GetOrdersResponseObject, error)
	// Deliver or refund orders for recipient
	// (PATCH /orders)
	UpdateOrders(ctx context.Context, request UpdateOrdersRequestObject) (UpdateOrdersResponseObject, error)
	// Accept an order from courier
	// (POST /orders)
	CreateOrder(ctx context.Context, request CreateOrderRequestObject) (CreateOrderResponseObject, error)
	// Retrieve orders history
	// (GET /orders-history)
	GetOrdersHistory(ctx context.Context, request GetOrdersHistoryRequestObject) (GetOrdersHistoryResponseObject, error)
	// Retrieve refunded orders
	// (GET /orders/refunds)
	GetRefundedOrders(ctx context.Context, request GetRefundedOrdersRequestObject) (GetRefundedOrdersResponseObject, error)
	// Return order to courier
	// (DELETE /orders/{orderID})
	DeleteOrder(ctx context.Context, request DeleteOrderRequestObject) (DeleteOrderResponseObject, error)
	// Retrieve order by ID for recipient
	// (GET /orders/{orderID})
	GetOrder(ctx context.Context, request GetOrderRequestObject) (GetOrderResponseObject, error)
	// Health check
	// (GET /ping)
	GetPing(ctx context.Context, request GetPingRequestObject) (GetPingResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetOrders operation middleware
func (sh *strictHandler) GetOrders(w http.ResponseWriter, r *http.Request, params GetOrdersParams) {
	var request GetOrdersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrders(ctx, request.(GetOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrdersResponseObject); ok {
		if err := validResponse.VisitGetOrdersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateOrders operation middleware
func (sh *strictHandler) UpdateOrders(w http.ResponseWriter, r *http.Request) {
	var request UpdateOrdersRequestObject

	var body UpdateOrdersJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateOrders(ctx, request.(UpdateOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateOrders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateOrdersResponseObject); ok {
		if err := validResponse.VisitUpdateOrdersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrder operation middleware
func (sh *strictHandler) CreateOrder(w http.ResponseWriter, r *http.Request) {
	var request CreateOrderRequestObject

	var body CreateOrderJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrder(ctx, request.(CreateOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateOrderResponseObject); ok {
		if err := validResponse.VisitCreateOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrdersHistory operation middleware
func (sh *strictHandler) GetOrdersHistory(w http.ResponseWriter, r *http.Request, params GetOrdersHistoryParams) {
	var request GetOrdersHistoryRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrdersHistory(ctx, request.(GetOrdersHistoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrdersHistory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrdersHistoryResponseObject); ok {
		if err := validResponse.VisitGetOrdersHistoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRefundedOrders operation middleware
func (sh *strictHandler) GetRefundedOrders(w http.ResponseWriter, r *http.Request, params GetRefundedOrdersParams) {
	var request GetRefundedOrdersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRefundedOrders(ctx, request.(GetRefundedOrdersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRefundedOrders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRefundedOrdersResponseObject); ok {
		if err := validResponse.VisitGetRefundedOrdersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteOrder operation middleware
func (sh *strictHandler) DeleteOrder(w http.ResponseWriter, r *http.Request, orderID OrderID, params DeleteOrderParams) {
	var request DeleteOrderRequestObject

	request.OrderID = orderID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteOrder(ctx, request.(DeleteOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteOrderResponseObject); ok {
		if err := validResponse.VisitDeleteOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrder operation middleware
func (sh *strictHandler) GetOrder(w http.ResponseWriter, r *http.Request, orderID OrderID, params GetOrderParams) {
	var request GetOrderRequestObject

	request.OrderID = orderID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrder(ctx, request.(GetOrderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrder")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOrderResponseObject); ok {
		if err := validResponse.VisitGetOrderResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPing operation middleware
func (sh *strictHandler) GetPing(w http.ResponseWriter, r *http.Request) {
	var request GetPingRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPing(ctx, request.(GetPingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPing")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPingResponseObject); ok {
		if err := validResponse.VisitGetPingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FnLbtw2F34Vgf+/VDxOanQxOycuEqMFYjhtN0Ew4EhHM0wkUiEpx64hIA2KokALZNNFV+0ruEUNTJvE",
	"eQXOGxW86DKSZqyxHbcGsrJFief2nfPx8MwxCliSMgpUCjQ8RinmOAEJ3DzFJCFS/0MoGqLnGfAj5COK",
	"E0BD99JHIphCgvVXIUQ4iyUa3t70UYIPSZIl+kE/EeqefCSPUr2fUAkT4CjPfcSiSMBSTe5tpyq0iUqJ",
	"QnJCJ1YgD4Hv7pQSUyynNYHurY84PM8IhxANJc+griFiPMHS2vnpFuo0m0NAUgJU1jQ1bK9/cjl1Rp9I",
	"GRVgwLnHAUt4qF3Zd+t6OWBUAjWxxGkakwBLwujgqWBUr1Ua/88hQkP0v0GVAQP7Vgwe2gCVco32EETA",
	"SarFoaFTH6LcR/dBfkAzupQ//LyuV3xBhLyQ8pSzFLgkNqImLcx/REIielpXQoU5x0cuLwqYHxdCn5Sf",
	"sfFTCORyr4IkHOGUjFgKVP8NWJIwWvzZTslnnLOrj3U/tV1m3wcKHMce6A88XuVMkd8mkjZarZiHEJMD",
	"4BCOQixhoRL0wi1JEmhXuI/gMCXc+LnmxikRkvGj9VDeh4DxsI21j0jYq3prXDFaY0uU0XDt0HCQGadr",
	"bxMSy6xfOB7ZT3MfvQAymcpFJSwbxzUNNEvG1p8XjMtpr28bNURC1AhgOwEqZEtXSvMK1e0i9G1eWjLb",
	"h+cZCNlO0gSSMccU79IgzkIw+DlBY8ZiwBQVZ06v+O3pU9bEL8XBMzwhdPKlEbd6797Cx51Eg5oi/bbx",
	"S6NQI/xubuybul2W6b1LNbuAtLReuMovUG3Xk8rnZnHflHWU1EGoNW4+vqIy12EWEidpXwQaXpcFWbeu",
	"Lnapm49Kc4Hq/tFEEMgBWEqwTGcEu3MEVbxpmIBxPIERuGfKKNSUVWExyr5KtUvbQRG8QqUTXoo+T8JS",
	"IsGl6HODv2BLwS4jEi72Jz3yunlirV0aS6pZtDnZudcF5l6T6IrYjtkh8tEYT2pU1Rnfng1KswSQ+lW9",
	"V7P5t+pEvVMzdeqps/kPaqZ+V3+rmebLRcYphFy8V7qLBRTN0mLorPCu8PRz7h4LF2OHwxF3ueajjOJM",
	"Thkn35hUjxgfkzAEatJejiKmM1cHWU5ZONJLOI7ZC1cXcoSDAFKJLYs5sSNdoiyT7lCFUcBoFJNAuj0k",
	"SWNIgEpXeHZTgGkAcWzWdBpxiuNLYFqdDg1kf1Mn85fqRL1Vp/NX85fzH1dji8OQ6K04HhEasQ6BP6sz",
	"9V6dqTc6Veav1Kl6M/9JvVMn89eemql38+/U2fyleqtO5t+rmV48q6s81f4WpdlytlmIBzgmoeH+Lt9+",
	"aWpTM6PtD3Wi3qiZ+rNatRafqr/q6i+ev1+Xdu3qKHVdcNbM36oiWowYuJS+/NXEFEeu81sIPIH1iaAF",
	"WFrm3eWtK1q+BiMY9yub16eGBlg98shl7bI8mr9u1U1EIA47U7oW69UNgBWxylG9o6hKSWSs39nbvbe9",
	"t4t8dABcWJ9ub2xubJoz0YYEDdEnG5sbd0zzK6fG5kF1mZ/YyZL2yAYqNJdWNztA/sLQ63E32NUnAzv3",
	"yv1zP3Rjq/xJY3BzZ3NzWU6V3w26Zxu5j7b67F5zhmCu9G6gdtWidcuZJQnWV260D5ITOAAPezER0mOR",
	"V6Ig8URU95gnpv5kMG1DZzujcp87dO6y8OhqB0+LvVy+mNKSZ5C3gN1qF6AR5ZUeeFpbDBJCT2RBAEJE",
	"WRwf3Xhkd2yL7JkJkO6RPVuAXmRWXJvYDTMTHQVaG29+SJAXb/69QL59fii7ZrM3HeFt0x56mFpkvYiz",
	"xAtYxolBqIlr7hccfKs2clvNxQ/KCc5HSr52Snb1Wk3RliM6sCW+8nTdd5fwj6fsvwdpMQhx2K7G9Nj9",
	"Kpa7sTzYedsisDtmvWLl//zpt2WturFAZrzgW8lWsK2/mlnRZYrjGuripqNUY1BvfOTt7vRpe9biw+In",
	"6x6MWP/JOdeaBqm+kq3g6j39vjtFap2WhEM5SGNMGj0WHGJd1GiIUmbkNK+CS37ovB50HgCO5dQLphA8",
	"q+EwNcuaAfP8nwAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../common/common.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
