version: "2"

services:
  goapp:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - ./.env
    ports:
      - "${BACKEND_HTTP_PORT}:${BACKEND_HTTP_PORT}"
      - "${BACKEND_GRPC_PORT}:${BACKEND_GRPC_PORT}"
    networks:
      - default

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-c",
          "kafka-topics --bootstrap-server localhost:9092 --list > /dev/null 2>&1",
        ]
      interval: 10s
      timeout: 10s
      retries: 10
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA_PORT}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_PORT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "${REDIS_INSIGHT_PORT}:${REDIS_INSIGHT_PORT}"
    depends_on:
      - redis

volumes:
  pgdata:
