// Code generated by MockGen. DO NOT EDIT.
// Source: outbox.go
//
// Generated by this command:
//
//	mockgen -source=outbox.go -destination=mocks/outbox.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	order_outbox "github.com/Staspol216/gh1/internal/infra/order_outbox"
	gomock "go.uber.org/mock/gomock"
)

// MockOutbox is a mock of Outbox interface.
type MockOutbox struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxMockRecorder
	isgomock struct{}
}

// MockOutboxMockRecorder is the mock recorder for MockOutbox.
type MockOutboxMockRecorder struct {
	mock *MockOutbox
}

// NewMockOutbox creates a new mock instance.
func NewMockOutbox(ctrl *gomock.Controller) *MockOutbox {
	mock := &MockOutbox{ctrl: ctrl}
	mock.recorder = &MockOutboxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutbox) EXPECT() *MockOutboxMockRecorder {
	return m.recorder
}

// AddTask mocks base method.
func (m *MockOutbox) AddTask(ctx context.Context, task *order_outbox.OrderOutboxTask) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTask", ctx, task)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTask indicates an expected call of AddTask.
func (mr *MockOutboxMockRecorder) AddTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTask", reflect.TypeOf((*MockOutbox)(nil).AddTask), ctx, task)
}

// DeleteTask mocks base method.
func (m *MockOutbox) DeleteTask(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockOutboxMockRecorder) DeleteTask(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockOutbox)(nil).DeleteTask), ctx, id)
}

// DeleteTasks mocks base method.
func (m *MockOutbox) DeleteTasks(ctx context.Context, ids []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTasks", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTasks indicates an expected call of DeleteTasks.
func (mr *MockOutboxMockRecorder) DeleteTasks(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTasks", reflect.TypeOf((*MockOutbox)(nil).DeleteTasks), ctx, ids)
}

// LockPending mocks base method.
func (m *MockOutbox) LockPending(ctx context.Context) ([]order_outbox.OrderOutboxTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockPending", ctx)
	ret0, _ := ret[0].([]order_outbox.OrderOutboxTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockPending indicates an expected call of LockPending.
func (mr *MockOutboxMockRecorder) LockPending(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockPending", reflect.TypeOf((*MockOutbox)(nil).LockPending), ctx)
}

// MarkTaskAsFailed mocks base method.
func (m *MockOutbox) MarkTaskAsFailed(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkTaskAsFailed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkTaskAsFailed indicates an expected call of MarkTaskAsFailed.
func (mr *MockOutboxMockRecorder) MarkTaskAsFailed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkTaskAsFailed", reflect.TypeOf((*MockOutbox)(nil).MarkTaskAsFailed), ctx, id)
}
