// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=mocks/storage.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	pvz_domain "github.com/Staspol216/gh1/internal/domain/order"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderStorage is a mock of OrderStorage interface.
type MockOrderStorage struct {
	ctrl     *gomock.Controller
	recorder *MockOrderStorageMockRecorder
	isgomock struct{}
}

// MockOrderStorageMockRecorder is the mock recorder for MockOrderStorage.
type MockOrderStorageMockRecorder struct {
	mock *MockOrderStorage
}

// NewMockOrderStorage creates a new mock instance.
func NewMockOrderStorage(ctrl *gomock.Controller) *MockOrderStorage {
	mock := &MockOrderStorage{ctrl: ctrl}
	mock.recorder = &MockOrderStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderStorage) EXPECT() *MockOrderStorageMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockOrderStorage) Add(ctx context.Context, newOrder *pvz_domain.Order) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, newOrder)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockOrderStorageMockRecorder) Add(ctx, newOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockOrderStorage)(nil).Add), ctx, newOrder)
}

// AddHistoryRecord mocks base method.
func (m *MockOrderStorage) AddHistoryRecord(ctx context.Context, record *pvz_domain.OrderRecord, orderId int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddHistoryRecord", ctx, record, orderId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddHistoryRecord indicates an expected call of AddHistoryRecord.
func (mr *MockOrderStorageMockRecorder) AddHistoryRecord(ctx, record, orderId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHistoryRecord", reflect.TypeOf((*MockOrderStorage)(nil).AddHistoryRecord), ctx, record, orderId)
}

// Delete mocks base method.
func (m *MockOrderStorage) Delete(ctx context.Context, orderId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, orderId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOrderStorageMockRecorder) Delete(ctx, orderId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrderStorage)(nil).Delete), ctx, orderId)
}

// GetAll mocks base method.
func (m *MockOrderStorage) GetAll(ctx context.Context) ([]*pvz_domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*pvz_domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockOrderStorageMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockOrderStorage)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockOrderStorage) GetByID(ctx context.Context, orderId int64) (*pvz_domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, orderId)
	ret0, _ := ret[0].(*pvz_domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOrderStorageMockRecorder) GetByID(ctx, orderId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOrderStorage)(nil).GetByID), ctx, orderId)
}

// GetByIDs mocks base method.
func (m *MockOrderStorage) GetByIDs(ctx context.Context, orderIds []int64) ([]*pvz_domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, orderIds)
	ret0, _ := ret[0].([]*pvz_domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockOrderStorageMockRecorder) GetByIDs(ctx, orderIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockOrderStorage)(nil).GetByIDs), ctx, orderIds)
}

// GetList mocks base method.
func (m *MockOrderStorage) GetList(ctx context.Context, pagination *pvz_domain.Pagination) ([]*pvz_domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, pagination)
	ret0, _ := ret[0].([]*pvz_domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockOrderStorageMockRecorder) GetList(ctx, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockOrderStorage)(nil).GetList), ctx, pagination)
}

// Update mocks base method.
func (m *MockOrderStorage) Update(ctx context.Context, updatedOrder *pvz_domain.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, updatedOrder)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOrderStorageMockRecorder) Update(ctx, updatedOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrderStorage)(nil).Update), ctx, updatedOrder)
}

// MockOrdersCache is a mock of OrdersCache interface.
type MockOrdersCache struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersCacheMockRecorder
	isgomock struct{}
}

// MockOrdersCacheMockRecorder is the mock recorder for MockOrdersCache.
type MockOrdersCacheMockRecorder struct {
	mock *MockOrdersCache
}

// NewMockOrdersCache creates a new mock instance.
func NewMockOrdersCache(ctrl *gomock.Controller) *MockOrdersCache {
	mock := &MockOrdersCache{ctrl: ctrl}
	mock.recorder = &MockOrdersCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersCache) EXPECT() *MockOrdersCacheMockRecorder {
	return m.recorder
}

// DeleteOrder mocks base method.
func (m *MockOrdersCache) DeleteOrder(ctx context.Context, orderId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrder", ctx, orderId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrder indicates an expected call of DeleteOrder.
func (mr *MockOrdersCacheMockRecorder) DeleteOrder(ctx, orderId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrder", reflect.TypeOf((*MockOrdersCache)(nil).DeleteOrder), ctx, orderId)
}

// GetOrder mocks base method.
func (m *MockOrdersCache) GetOrder(ctx context.Context, id any) (*pvz_domain.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, id)
	ret0, _ := ret[0].(*pvz_domain.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockOrdersCacheMockRecorder) GetOrder(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockOrdersCache)(nil).GetOrder), ctx, id)
}

// SetOrder mocks base method.
func (m *MockOrdersCache) SetOrder(ctx context.Context, order *pvz_domain.Order, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOrder", ctx, order, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOrder indicates an expected call of SetOrder.
func (mr *MockOrdersCacheMockRecorder) SetOrder(ctx, order, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOrder", reflect.TypeOf((*MockOrdersCache)(nil).SetOrder), ctx, order, ttl)
}
