// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: cmd/api/orders.proto

package orders_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_RECEVIED     OrderStatus = 0
	OrderStatus_RETURNED     OrderStatus = 1
	OrderStatus_DELIVERED    OrderStatus = 2
	OrderStatus_REFUNDED     OrderStatus = 3
	OrderStatus_STRAGE_ENDED OrderStatus = 4
	OrderStatus_NONE         OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "RECEVIED",
		1: "RETURNED",
		2: "DELIVERED",
		3: "REFUNDED",
		4: "STRAGE_ENDED",
		5: "NONE",
	}
	OrderStatus_value = map[string]int32{
		"RECEVIED":     0,
		"RETURNED":     1,
		"DELIVERED":    2,
		"REFUNDED":     3,
		"STRAGE_ENDED": 4,
		"NONE":         5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_api_orders_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_cmd_api_orders_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_cmd_api_orders_proto_rawDescGZIP(), []int{0}
}

type OrderRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=orders.proto.OrderStatus" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderRecord) Reset() {
	*x = OrderRecord{}
	mi := &file_cmd_api_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderRecord) ProtoMessage() {}

func (x *OrderRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_api_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderRecord.ProtoReflect.Descriptor instead.
func (*OrderRecord) Descriptor() ([]byte, []int) {
	return file_cmd_api_orders_proto_rawDescGZIP(), []int{0}
}

func (x *OrderRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *OrderRecord) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_RECEVIED
}

func (x *OrderRecord) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Order struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RecipientId    int64                  `protobuf:"varint,2,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	ExpirationDate *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	DeliveredDate  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=delivered_date,json=deliveredDate,proto3" json:"delivered_date,omitempty"`
	RefundedDate   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=refunded_date,json=refundedDate,proto3" json:"refunded_date,omitempty"`
	Status         OrderStatus            `protobuf:"varint,6,opt,name=status,proto3,enum=orders.proto.OrderStatus" json:"status,omitempty"`
	History        []*OrderRecord         `protobuf:"bytes,7,rep,name=history,proto3" json:"history,omitempty"`
	Weight         float64                `protobuf:"fixed64,8,opt,name=Weight,proto3" json:"Weight,omitempty"`
	Worth          float64                `protobuf:"fixed64,9,opt,name=Worth,proto3" json:"Worth,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_cmd_api_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_api_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_cmd_api_orders_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetRecipientId() int64 {
	if x != nil {
		return x.RecipientId
	}
	return 0
}

func (x *Order) GetExpirationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationDate
	}
	return nil
}

func (x *Order) GetDeliveredDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredDate
	}
	return nil
}

func (x *Order) GetRefundedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RefundedDate
	}
	return nil
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_RECEVIED
}

func (x *Order) GetHistory() []*OrderRecord {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *Order) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Order) GetWorth() float64 {
	if x != nil {
		return x.Worth
	}
	return 0
}

type GetOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersRequest) Reset() {
	*x = GetOrdersRequest{}
	mi := &file_cmd_api_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersRequest) ProtoMessage() {}

func (x *GetOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_api_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersRequest) Descriptor() ([]byte, []int) {
	return file_cmd_api_orders_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrdersRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetOrdersRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse) Reset() {
	*x = GetOrdersResponse{}
	mi := &file_cmd_api_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse) ProtoMessage() {}

func (x *GetOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_api_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return file_cmd_api_orders_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type CreateOrderRequest struct {
	state            protoimpl.MessageState          `protogen:"open.v1"`
	Order            *CreateOrderRequest_OrderParams `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	PackagingType    string                          `protobuf:"bytes,2,opt,name=packaging_type,json=packagingType,proto3" json:"packaging_type,omitempty"`
	MembranaIncluded bool                            `protobuf:"varint,3,opt,name=membrana_included,json=membranaIncluded,proto3" json:"membrana_included,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_cmd_api_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_api_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_cmd_api_orders_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrderRequest) GetOrder() *CreateOrderRequest_OrderParams {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *CreateOrderRequest) GetPackagingType() string {
	if x != nil {
		return x.PackagingType
	}
	return ""
}

func (x *CreateOrderRequest) GetMembranaIncluded() bool {
	if x != nil {
		return x.MembranaIncluded
	}
	return false
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_cmd_api_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_api_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_cmd_api_orders_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrderResponse) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type UpdateOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderIds      []int64                `protobuf:"varint,1,rep,packed,name=order_ids,json=orderIds,proto3" json:"order_ids,omitempty"`
	RecipientId   int64                  `protobuf:"varint,2,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrdersRequest) Reset() {
	*x = UpdateOrdersRequest{}
	mi := &file_cmd_api_orders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrdersRequest) ProtoMessage() {}

func (x *UpdateOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_api_orders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrdersRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrdersRequest) Descriptor() ([]byte, []int) {
	return file_cmd_api_orders_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateOrdersRequest) GetOrderIds() []int64 {
	if x != nil {
		return x.OrderIds
	}
	return nil
}

func (x *UpdateOrdersRequest) GetRecipientId() int64 {
	if x != nil {
		return x.RecipientId
	}
	return 0
}

func (x *UpdateOrdersRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type UpdateOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrdersResponse) Reset() {
	*x = UpdateOrdersResponse{}
	mi := &file_cmd_api_orders_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrdersResponse) ProtoMessage() {}

func (x *UpdateOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_api_orders_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrdersResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrdersResponse) Descriptor() ([]byte, []int) {
	return file_cmd_api_orders_proto_rawDescGZIP(), []int{7}
}

type DeleteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderRequest) Reset() {
	*x = DeleteOrderRequest{}
	mi := &file_cmd_api_orders_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderRequest) ProtoMessage() {}

func (x *DeleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_api_orders_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_cmd_api_orders_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type DeleteOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderResponse) Reset() {
	*x = DeleteOrderResponse{}
	mi := &file_cmd_api_orders_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderResponse) ProtoMessage() {}

func (x *DeleteOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_api_orders_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderResponse.ProtoReflect.Descriptor instead.
func (*DeleteOrderResponse) Descriptor() ([]byte, []int) {
	return file_cmd_api_orders_proto_rawDescGZIP(), []int{9}
}

type CreateOrderRequest_OrderParams struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecipientId    int64                  `protobuf:"varint,1,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	ExpirationDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	Weight         float64                `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Worth          float64                `protobuf:"fixed64,4,opt,name=worth,proto3" json:"worth,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrderRequest_OrderParams) Reset() {
	*x = CreateOrderRequest_OrderParams{}
	mi := &file_cmd_api_orders_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest_OrderParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest_OrderParams) ProtoMessage() {}

func (x *CreateOrderRequest_OrderParams) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_api_orders_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest_OrderParams.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest_OrderParams) Descriptor() ([]byte, []int) {
	return file_cmd_api_orders_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CreateOrderRequest_OrderParams) GetRecipientId() int64 {
	if x != nil {
		return x.RecipientId
	}
	return 0
}

func (x *CreateOrderRequest_OrderParams) GetExpirationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationDate
	}
	return nil
}

func (x *CreateOrderRequest_OrderParams) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateOrderRequest_OrderParams) GetWorth() float64 {
	if x != nil {
		return x.Worth
	}
	return 0
}

var File_cmd_api_orders_proto protoreflect.FileDescriptor

const file_cmd_api_orders_proto_rawDesc = "" +
	"\n" +
	"\x14cmd/api/orders.proto\x12\forders.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x01\n" +
	"\vOrderRecord\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.orders.proto.OrderStatusR\x06status\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x99\x03\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\frecipient_id\x18\x02 \x01(\x03R\vrecipientId\x12C\n" +
	"\x0fexpiration_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0eexpirationDate\x12A\n" +
	"\x0edelivered_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rdeliveredDate\x12?\n" +
	"\rrefunded_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\frefundedDate\x121\n" +
	"\x06status\x18\x06 \x01(\x0e2\x19.orders.proto.OrderStatusR\x06status\x123\n" +
	"\ahistory\x18\a \x03(\v2\x19.orders.proto.OrderRecordR\ahistory\x12\x16\n" +
	"\x06Weight\x18\b \x01(\x01R\x06Weight\x12\x14\n" +
	"\x05Worth\x18\t \x01(\x01R\x05Worth\"@\n" +
	"\x10GetOrdersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"@\n" +
	"\x11GetOrdersResponse\x12+\n" +
	"\x06orders\x18\x01 \x03(\v2\x13.orders.proto.OrderR\x06orders\"\xd2\x02\n" +
	"\x12CreateOrderRequest\x12B\n" +
	"\x05order\x18\x01 \x01(\v2,.orders.proto.CreateOrderRequest.OrderParamsR\x05order\x12%\n" +
	"\x0epackaging_type\x18\x02 \x01(\tR\rpackagingType\x12+\n" +
	"\x11membrana_included\x18\x03 \x01(\bR\x10membranaIncluded\x1a\xa3\x01\n" +
	"\vOrderParams\x12!\n" +
	"\frecipient_id\x18\x01 \x01(\x03R\vrecipientId\x12C\n" +
	"\x0fexpiration_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0eexpirationDate\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x01R\x06weight\x12\x14\n" +
	"\x05worth\x18\x04 \x01(\x01R\x05worth\"0\n" +
	"\x13CreateOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"m\n" +
	"\x13UpdateOrdersRequest\x12\x1b\n" +
	"\torder_ids\x18\x01 \x03(\x03R\borderIds\x12!\n" +
	"\frecipient_id\x18\x02 \x01(\x03R\vrecipientId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"\x16\n" +
	"\x14UpdateOrdersResponse\"/\n" +
	"\x12DeleteOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"\x15\n" +
	"\x13DeleteOrderResponse*b\n" +
	"\vOrderStatus\x12\f\n" +
	"\bRECEVIED\x10\x00\x12\f\n" +
	"\bRETURNED\x10\x01\x12\r\n" +
	"\tDELIVERED\x10\x02\x12\f\n" +
	"\bREFUNDED\x10\x03\x12\x10\n" +
	"\fSTRAGE_ENDED\x10\x04\x12\b\n" +
	"\x04NONE\x10\x052\xdc\x02\n" +
	"\rOrdersService\x12L\n" +
	"\tGetOrders\x12\x1e.orders.proto.GetOrdersRequest\x1a\x1f.orders.proto.GetOrdersResponse\x12U\n" +
	"\fUpdateOrders\x12!.orders.proto.UpdateOrdersRequest\x1a\".orders.proto.UpdateOrdersResponse\x12R\n" +
	"\vCreateOrder\x12 .orders.proto.CreateOrderRequest\x1a!.orders.proto.CreateOrderResponse\x12R\n" +
	"\vDeleteOrder\x12 .orders.proto.DeleteOrderRequest\x1a!.orders.proto.DeleteOrderResponseB\x0eZ\forders.protob\x06proto3"

var (
	file_cmd_api_orders_proto_rawDescOnce sync.Once
	file_cmd_api_orders_proto_rawDescData []byte
)

func file_cmd_api_orders_proto_rawDescGZIP() []byte {
	file_cmd_api_orders_proto_rawDescOnce.Do(func() {
		file_cmd_api_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_api_orders_proto_rawDesc), len(file_cmd_api_orders_proto_rawDesc)))
	})
	return file_cmd_api_orders_proto_rawDescData
}

var file_cmd_api_orders_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmd_api_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_cmd_api_orders_proto_goTypes = []any{
	(OrderStatus)(0),                       // 0: orders.proto.OrderStatus
	(*OrderRecord)(nil),                    // 1: orders.proto.OrderRecord
	(*Order)(nil),                          // 2: orders.proto.Order
	(*GetOrdersRequest)(nil),               // 3: orders.proto.GetOrdersRequest
	(*GetOrdersResponse)(nil),              // 4: orders.proto.GetOrdersResponse
	(*CreateOrderRequest)(nil),             // 5: orders.proto.CreateOrderRequest
	(*CreateOrderResponse)(nil),            // 6: orders.proto.CreateOrderResponse
	(*UpdateOrdersRequest)(nil),            // 7: orders.proto.UpdateOrdersRequest
	(*UpdateOrdersResponse)(nil),           // 8: orders.proto.UpdateOrdersResponse
	(*DeleteOrderRequest)(nil),             // 9: orders.proto.DeleteOrderRequest
	(*DeleteOrderResponse)(nil),            // 10: orders.proto.DeleteOrderResponse
	(*CreateOrderRequest_OrderParams)(nil), // 11: orders.proto.CreateOrderRequest.OrderParams
	(*timestamppb.Timestamp)(nil),          // 12: google.protobuf.Timestamp
}
var file_cmd_api_orders_proto_depIdxs = []int32{
	12, // 0: orders.proto.OrderRecord.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: orders.proto.OrderRecord.status:type_name -> orders.proto.OrderStatus
	12, // 2: orders.proto.Order.expiration_date:type_name -> google.protobuf.Timestamp
	12, // 3: orders.proto.Order.delivered_date:type_name -> google.protobuf.Timestamp
	12, // 4: orders.proto.Order.refunded_date:type_name -> google.protobuf.Timestamp
	0,  // 5: orders.proto.Order.status:type_name -> orders.proto.OrderStatus
	1,  // 6: orders.proto.Order.history:type_name -> orders.proto.OrderRecord
	2,  // 7: orders.proto.GetOrdersResponse.orders:type_name -> orders.proto.Order
	11, // 8: orders.proto.CreateOrderRequest.order:type_name -> orders.proto.CreateOrderRequest.OrderParams
	12, // 9: orders.proto.CreateOrderRequest.OrderParams.expiration_date:type_name -> google.protobuf.Timestamp
	3,  // 10: orders.proto.OrdersService.GetOrders:input_type -> orders.proto.GetOrdersRequest
	7,  // 11: orders.proto.OrdersService.UpdateOrders:input_type -> orders.proto.UpdateOrdersRequest
	5,  // 12: orders.proto.OrdersService.CreateOrder:input_type -> orders.proto.CreateOrderRequest
	9,  // 13: orders.proto.OrdersService.DeleteOrder:input_type -> orders.proto.DeleteOrderRequest
	4,  // 14: orders.proto.OrdersService.GetOrders:output_type -> orders.proto.GetOrdersResponse
	8,  // 15: orders.proto.OrdersService.UpdateOrders:output_type -> orders.proto.UpdateOrdersResponse
	6,  // 16: orders.proto.OrdersService.CreateOrder:output_type -> orders.proto.CreateOrderResponse
	10, // 17: orders.proto.OrdersService.DeleteOrder:output_type -> orders.proto.DeleteOrderResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_cmd_api_orders_proto_init() }
func file_cmd_api_orders_proto_init() {
	if File_cmd_api_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_api_orders_proto_rawDesc), len(file_cmd_api_orders_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_api_orders_proto_goTypes,
		DependencyIndexes: file_cmd_api_orders_proto_depIdxs,
		EnumInfos:         file_cmd_api_orders_proto_enumTypes,
		MessageInfos:      file_cmd_api_orders_proto_msgTypes,
	}.Build()
	File_cmd_api_orders_proto = out.File
	file_cmd_api_orders_proto_goTypes = nil
	file_cmd_api_orders_proto_depIdxs = nil
}
