// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: cmd/api/proto/common.proto

package common_proto

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiErrorCode int32

const (
	ApiErrorCode_bad_request        ApiErrorCode = 0
	ApiErrorCode_unauthorized       ApiErrorCode = 1
	ApiErrorCode_forbidden          ApiErrorCode = 2
	ApiErrorCode_not_found          ApiErrorCode = 3
	ApiErrorCode_method_not_allowed ApiErrorCode = 4
	ApiErrorCode_not_acceptable     ApiErrorCode = 5
	ApiErrorCode_request_timeout    ApiErrorCode = 6
	ApiErrorCode_state_conflict     ApiErrorCode = 7
	ApiErrorCode_not_implemented    ApiErrorCode = 8
	ApiErrorCode_request_cancelled  ApiErrorCode = 9
	ApiErrorCode_internal           ApiErrorCode = 10
)

// Enum value maps for ApiErrorCode.
var (
	ApiErrorCode_name = map[int32]string{
		0:  "bad_request",
		1:  "unauthorized",
		2:  "forbidden",
		3:  "not_found",
		4:  "method_not_allowed",
		5:  "not_acceptable",
		6:  "request_timeout",
		7:  "state_conflict",
		8:  "not_implemented",
		9:  "request_cancelled",
		10: "internal",
	}
	ApiErrorCode_value = map[string]int32{
		"bad_request":        0,
		"unauthorized":       1,
		"forbidden":          2,
		"not_found":          3,
		"method_not_allowed": 4,
		"not_acceptable":     5,
		"request_timeout":    6,
		"state_conflict":     7,
		"not_implemented":    8,
		"request_cancelled":  9,
		"internal":           10,
	}
)

func (x ApiErrorCode) Enum() *ApiErrorCode {
	p := new(ApiErrorCode)
	*p = x
	return p
}

func (x ApiErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_api_proto_common_proto_enumTypes[0].Descriptor()
}

func (ApiErrorCode) Type() protoreflect.EnumType {
	return &file_cmd_api_proto_common_proto_enumTypes[0]
}

func (x ApiErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiErrorCode.Descriptor instead.
func (ApiErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_cmd_api_proto_common_proto_rawDescGZIP(), []int{0}
}

type ApiError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *BaseError             `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiError) Reset() {
	*x = ApiError{}
	mi := &file_cmd_api_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiError) ProtoMessage() {}

func (x *ApiError) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_api_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiError.ProtoReflect.Descriptor instead.
func (*ApiError) Descriptor() ([]byte, []int) {
	return file_cmd_api_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *ApiError) GetError() *BaseError {
	if x != nil {
		return x.Error
	}
	return nil
}

type BaseError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ApiErrorCode           `protobuf:"varint,1,opt,name=code,proto3,enum=common.proto.ApiErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Params        *ApiErrorParams        `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseError) Reset() {
	*x = BaseError{}
	mi := &file_cmd_api_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseError) ProtoMessage() {}

func (x *BaseError) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_api_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseError.ProtoReflect.Descriptor instead.
func (*BaseError) Descriptor() ([]byte, []int) {
	return file_cmd_api_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *BaseError) GetCode() ApiErrorCode {
	if x != nil {
		return x.Code
	}
	return ApiErrorCode_bad_request
}

func (x *BaseError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BaseError) GetParams() *ApiErrorParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type ApiErrorParams struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Validations    []*ValidationInfo      `protobuf:"bytes,1,rep,name=validations,proto3" json:"validations,omitempty"`
	AdditionalInfo []string               `protobuf:"bytes,2,rep,name=additional_info,proto3" json:"additional_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApiErrorParams) Reset() {
	*x = ApiErrorParams{}
	mi := &file_cmd_api_proto_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiErrorParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiErrorParams) ProtoMessage() {}

func (x *ApiErrorParams) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_api_proto_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiErrorParams.ProtoReflect.Descriptor instead.
func (*ApiErrorParams) Descriptor() ([]byte, []int) {
	return file_cmd_api_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *ApiErrorParams) GetValidations() []*ValidationInfo {
	if x != nil {
		return x.Validations
	}
	return nil
}

func (x *ApiErrorParams) GetAdditionalInfo() []string {
	if x != nil {
		return x.AdditionalInfo
	}
	return nil
}

type ValidationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationInfo) Reset() {
	*x = ValidationInfo{}
	mi := &file_cmd_api_proto_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationInfo) ProtoMessage() {}

func (x *ValidationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_api_proto_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationInfo.ProtoReflect.Descriptor instead.
func (*ValidationInfo) Descriptor() ([]byte, []int) {
	return file_cmd_api_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *ValidationInfo) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_cmd_api_proto_common_proto protoreflect.FileDescriptor

const file_cmd_api_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x1acmd/api/proto/common.proto\x12\fcommon.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"g\n" +
	"\bApiError\x12-\n" +
	"\x05error\x18\x01 \x01(\v2\x17.common.proto.BaseErrorR\x05error:,\x92A)\n" +
	"'2\x1dОписание ошибки\xd2\x01\x05error\"\xc7\x01\n" +
	"\tBaseError\x12.\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1a.common.proto.ApiErrorCodeR\x04code\x12<\n" +
	"\amessage\x18\x02 \x01(\tB\"\x92A\x1f2\x1dОписание ошибкиR\amessage\x124\n" +
	"\x06params\x18\x03 \x01(\v2\x1c.common.proto.ApiErrorParamsR\x06params:\x16\x92A\x13\n" +
	"\x11\xd2\x01\x04code\xd2\x01\amessage\"\xa6\x02\n" +
	"\x0eApiErrorParams\x12z\n" +
	"\vvalidations\x18\x01 \x03(\v2\x1c.common.proto.ValidationInfoB:\x92A725Информации о валидации полейR\vvalidations\x12p\n" +
	"\x0fadditional_info\x18\x02 \x03(\tBF\x92AC2AДополнительная информация о ошибкеR\x0fadditional_info:&\x92A#\n" +
	"!2\x1fПараметры ошибки\"\x8e\x01\n" +
	"\x0eValidationInfo\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage:L\x92AI\n" +
	"G23Информация о валидации поля\xd2\x01\x05field\xd2\x01\amessage*\xde\x01\n" +
	"\fApiErrorCode\x12\x0f\n" +
	"\vbad_request\x10\x00\x12\x10\n" +
	"\funauthorized\x10\x01\x12\r\n" +
	"\tforbidden\x10\x02\x12\r\n" +
	"\tnot_found\x10\x03\x12\x16\n" +
	"\x12method_not_allowed\x10\x04\x12\x12\n" +
	"\x0enot_acceptable\x10\x05\x12\x13\n" +
	"\x0frequest_timeout\x10\x06\x12\x12\n" +
	"\x0estate_conflict\x10\a\x12\x13\n" +
	"\x0fnot_implemented\x10\b\x12\x15\n" +
	"\x11request_cancelled\x10\t\x12\f\n" +
	"\binternal\x10\n" +
	"B\x0eZ\fcommon.protob\x06proto3"

var (
	file_cmd_api_proto_common_proto_rawDescOnce sync.Once
	file_cmd_api_proto_common_proto_rawDescData []byte
)

func file_cmd_api_proto_common_proto_rawDescGZIP() []byte {
	file_cmd_api_proto_common_proto_rawDescOnce.Do(func() {
		file_cmd_api_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_api_proto_common_proto_rawDesc), len(file_cmd_api_proto_common_proto_rawDesc)))
	})
	return file_cmd_api_proto_common_proto_rawDescData
}

var file_cmd_api_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmd_api_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cmd_api_proto_common_proto_goTypes = []any{
	(ApiErrorCode)(0),      // 0: common.proto.ApiErrorCode
	(*ApiError)(nil),       // 1: common.proto.ApiError
	(*BaseError)(nil),      // 2: common.proto.BaseError
	(*ApiErrorParams)(nil), // 3: common.proto.ApiErrorParams
	(*ValidationInfo)(nil), // 4: common.proto.ValidationInfo
}
var file_cmd_api_proto_common_proto_depIdxs = []int32{
	2, // 0: common.proto.ApiError.error:type_name -> common.proto.BaseError
	0, // 1: common.proto.BaseError.code:type_name -> common.proto.ApiErrorCode
	3, // 2: common.proto.BaseError.params:type_name -> common.proto.ApiErrorParams
	4, // 3: common.proto.ApiErrorParams.validations:type_name -> common.proto.ValidationInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_cmd_api_proto_common_proto_init() }
func file_cmd_api_proto_common_proto_init() {
	if File_cmd_api_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_api_proto_common_proto_rawDesc), len(file_cmd_api_proto_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_api_proto_common_proto_goTypes,
		DependencyIndexes: file_cmd_api_proto_common_proto_depIdxs,
		EnumInfos:         file_cmd_api_proto_common_proto_enumTypes,
		MessageInfos:      file_cmd_api_proto_common_proto_msgTypes,
	}.Build()
	File_cmd_api_proto_common_proto = out.File
	file_cmd_api_proto_common_proto_goTypes = nil
	file_cmd_api_proto_common_proto_depIdxs = nil
}
