// Package common_dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package common_dto

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for ApiErrorCode.
const (
	BadRequest       ApiErrorCode = "bad_request"
	Forbidden        ApiErrorCode = "forbidden"
	Internal         ApiErrorCode = "internal"
	MethodNotAllowed ApiErrorCode = "method_not_allowed"
	NotAcceptable    ApiErrorCode = "not_acceptable"
	NotFound         ApiErrorCode = "not_found"
	NotImplemented   ApiErrorCode = "not_implemented"
	RequestCancelled ApiErrorCode = "request_cancelled"
	RequestTimeout   ApiErrorCode = "request_timeout"
	StateConflict    ApiErrorCode = "state_conflict"
	Unauthorized     ApiErrorCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ApiErrorCode enum.
func (e ApiErrorCode) Valid() bool {
	switch e {
	case BadRequest:
		return true
	case Forbidden:
		return true
	case Internal:
		return true
	case MethodNotAllowed:
		return true
	case NotAcceptable:
		return true
	case NotFound:
		return true
	case NotImplemented:
		return true
	case RequestCancelled:
		return true
	case RequestTimeout:
		return true
	case StateConflict:
		return true
	case Unauthorized:
		return true
	default:
		return false
	}
}

// ApiError Описание ошибки
type ApiError struct {
	Error BaseError `json:"error"`
}

// ApiErrorCode defines model for ApiErrorCode.
type ApiErrorCode string

// ApiErrorParams Параметры ошибки
type ApiErrorParams struct {
	// AdditionalInfo Дополнительная информация о ошибке
	AdditionalInfo *[]string `json:"additional_info,omitempty"`

	// Validations Информации о валидации полей
	Validations *[]ValidationInfo `json:"validations,omitempty"`
}

// BaseError defines model for BaseError.
type BaseError struct {
	Code ApiErrorCode `json:"code"`

	// Message Описание ошибки
	Message string `json:"message"`

	// Params Параметры ошибки
	Params *ApiErrorParams `json:"params,omitempty"`
}

// ValidationInfo Информация о валидации поля
type ValidationInfo struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// ApiErrorResponse Описание ошибки
type ApiErrorResponse = ApiError

type ApiErrorResponseJSONResponse ApiError

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"lFPBbhM7FP2V6L63HDV97+1m11ch1BUVCzYIRc7MncaV59rYnqJSjVQqhJBA6oYFK/iFgIg00Db9hTt/",
	"hDwzaUIyRGVnH/uee8718RkkOjeakLyD+AwsOqPJYbPZM/KBtdo+7sCAJZo8kg9LYYySifBS0/DYaQqY",
	"SyaYi7D622IGMfw1XDYYtqduuCCGsiwjSNElVprAAzE8REIr1ADDhcFCD4SLXfmqtLD+tZ4/8S1X9Sue",
	"8g1XPBvwvH7LFX/hH1xBBMZqg9bL1iIuSLbJ/V84XOiNwOLzQlpMIX7alT+LwJ8ahBj0+BgTD2V0J3Bf",
	"p83ckIo8VIxFOgoM6DxEUJAo/ERb+RJTiCDTdizTFAkiIO1HmS4o4Dn6iU5HARJK6RfN5WaXJGi8GCuE",
	"Vhg6P/IyR10EeueFx1GiKVMy8V2NzI3CHMk3LIuiRFCCSjWYJI+WhFox5ryVdLRq7FBYkbue+X/maX3O",
	"U77mWX1Rn9fvtr+ASFMZSoUaScp0D+EHnvMtz/kqPGh9wTO+qt/zDU/rywFXfFO/5nl9ztc8rd9wFcD5",
	"astZcOSx1bphpwOEteI07E+EkmmT6T5vH9e7cdV0+8pTvuKKvy3RVvGMv6+235ayJ3edD8IcNrSVPSlb",
	"JjM+W5tr0gXvPv+wCWkZcuacOMI//1QbYzV36bhP/y5L67+rsbBU1ffN1oZ2jxfr8vG7F6svNxKaSVRp",
	"b3hW5rV2tuakpdhmJVT0539f57mmAZKXjaIIvPQKlyePDNLe4cEgxUySbKMbwQla1xL8s7MbxGqDJIyE",
	"GP7b2d35N9gUfuIgpkKp8mcAAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
