// Code generated by MockGen. DO NOT EDIT.
// Source: tx.go
//
// Generated by this command:
//
//	mockgen -source=tx.go -destination=mocks/tx.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pvz_ports "github.com/Staspol216/gh1/internal/ports"
	pgconn "github.com/jackc/pgconn"
	pgx "github.com/jackc/pgx/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockQueryEngine is a mock of QueryEngine interface.
type MockQueryEngine struct {
	ctrl     *gomock.Controller
	recorder *MockQueryEngineMockRecorder
	isgomock struct{}
}

// MockQueryEngineMockRecorder is the mock recorder for MockQueryEngine.
type MockQueryEngineMockRecorder struct {
	mock *MockQueryEngine
}

// NewMockQueryEngine creates a new mock instance.
func NewMockQueryEngine(ctrl *gomock.Controller) *MockQueryEngine {
	mock := &MockQueryEngine{ctrl: ctrl}
	mock.recorder = &MockQueryEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryEngine) EXPECT() *MockQueryEngineMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockQueryEngine) Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range arguments {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockQueryEngineMockRecorder) Exec(ctx, sql any, arguments ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, arguments...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockQueryEngine)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MockQueryEngine) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockQueryEngineMockRecorder) Query(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockQueryEngine)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockQueryEngine) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockQueryEngineMockRecorder) QueryRow(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockQueryEngine)(nil).QueryRow), varargs...)
}

// MockTransactionManager is a mock of TransactionManager interface.
type MockTransactionManager struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionManagerMockRecorder
	isgomock struct{}
}

// MockTransactionManagerMockRecorder is the mock recorder for MockTransactionManager.
type MockTransactionManagerMockRecorder struct {
	mock *MockTransactionManager
}

// NewMockTransactionManager creates a new mock instance.
func NewMockTransactionManager(ctrl *gomock.Controller) *MockTransactionManager {
	mock := &MockTransactionManager{ctrl: ctrl}
	mock.recorder = &MockTransactionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionManager) EXPECT() *MockTransactionManagerMockRecorder {
	return m.recorder
}

// GetQueryEngine mocks base method.
func (m *MockTransactionManager) GetQueryEngine(ctxTx context.Context) pvz_ports.QueryEngine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueryEngine", ctxTx)
	ret0, _ := ret[0].(pvz_ports.QueryEngine)
	return ret0
}

// GetQueryEngine indicates an expected call of GetQueryEngine.
func (mr *MockTransactionManagerMockRecorder) GetQueryEngine(ctxTx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueryEngine", reflect.TypeOf((*MockTransactionManager)(nil).GetQueryEngine), ctxTx)
}

// RunReadCommitted mocks base method.
func (m *MockTransactionManager) RunReadCommitted(fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunReadCommitted", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunReadCommitted indicates an expected call of RunReadCommitted.
func (mr *MockTransactionManagerMockRecorder) RunReadCommitted(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunReadCommitted", reflect.TypeOf((*MockTransactionManager)(nil).RunReadCommitted), fn)
}

// RunRepeatableRead mocks base method.
func (m *MockTransactionManager) RunRepeatableRead(fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunRepeatableRead", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunRepeatableRead indicates an expected call of RunRepeatableRead.
func (mr *MockTransactionManagerMockRecorder) RunRepeatableRead(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunRepeatableRead", reflect.TypeOf((*MockTransactionManager)(nil).RunRepeatableRead), fn)
}

// RunSerializable mocks base method.
func (m *MockTransactionManager) RunSerializable(fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunSerializable", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunSerializable indicates an expected call of RunSerializable.
func (mr *MockTransactionManagerMockRecorder) RunSerializable(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunSerializable", reflect.TypeOf((*MockTransactionManager)(nil).RunSerializable), fn)
}
